# Generated by Django 4.2.4 on 2023-08-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
