# Generated by Django 4.2.4 on 2023-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0002_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('sets', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(to='nebulaApp.exercise')),
            ],
        ),
    ]
