# Generated by Django 4.2.4 on 2023-08-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0003_exercise_fitnessplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='image',
            field=models.URLField(default='https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_842,ar_1.2,q_auto:eco,dpr_2,f_auto,fl_progressive/image/test/sku-card-widget/gold2.png'),
        ),
    ]
