# Generated by Django 4.2.4 on 2023-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0004_fitnessplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='image',
            field=models.URLField(),
        ),
    ]
