# Generated by Django 4.2.4 on 2023-09-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0006_trainerinfo_users_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('is_trianer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainerinfo',
            name='users',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
