# Generated by Django 4.2.4 on 2023-09-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0007_userregister_remove_trainerinfo_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='is_trianer',
        ),
    ]
