# Generated by Django 4.2.4 on 2023-09-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0011_customuser_delete_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
