# Generated by Django 4.2.4 on 2023-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0014_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainerinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='trainerinfo',
            name='image',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/5087/5087579.png'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/5087/5087579.png'),
        ),
    ]
